export default {
  kind: "customsearch#search",
  url: {
    type: "application/json",
    template:
      "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
  },
  queries: {
    request: [
      {
        title: "Google Custom Search - next js",
        totalResults: "13700000000",
        searchTerms: "next js",
        count: 10,
        startIndex: 1,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "06aaf7237d4b74408",
        searchType: "image",
      },
    ],
    nextPage: [
      {
        title: "Google Custom Search - next js",
        totalResults: "13700000000",
        searchTerms: "next js",
        count: 10,
        startIndex: 11,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "06aaf7237d4b74408",
        searchType: "image",
      },
    ],
  },
  context: {
    title: "goog-clone",
  },
  searchInformation: {
    searchTime: 0.184307,
    formattedSearchTime: "0.18",
    totalResults: "13700000000",
    formattedTotalResults: "13,700,000,000",
  },
  items: [
    {
      kind: "customsearch#result",
      title: "File:Nextjs-logo.svg - Wikipedia",
      htmlTitle: "File:<b>Nextjs</b>-logo.svg - Wikipedia",
      link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nextjs-logo.svg/2560px-Nextjs-logo.svg.png",
      displayLink: "en.wikipedia.org",
      snippet: "File:Nextjs-logo.svg - Wikipedia",
      htmlSnippet: "File:<b>Nextjs</b>-logo.svg - Wikipedia",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://en.wikipedia.org/wiki/File:Nextjs-logo.svg",
        height: 1534,
        width: 2560,
        byteSize: 46897,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQo6KkRWa-svTbEy_tVIOqs9TUNaQIl3E-EK_ocaQmAgJ-fkKkLhy5sgk&s",
        thumbnailHeight: 90,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Different forms of Pre-rendering in NextJS - GeeksforGeeks",
      htmlTitle:
        "Different forms of Pre-rendering in <b>NextJS</b> - GeeksforGeeks",
      link: "https://media.geeksforgeeks.org/wp-content/cdn-uploads/20220311094050/User-send-a-request-to.png",
      displayLink: "www.geeksforgeeks.org",
      snippet: "Different forms of Pre-rendering in NextJS - GeeksforGeeks",
      htmlSnippet:
        "Different forms of Pre-rendering in <b>NextJS</b> - GeeksforGeeks",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink:
          "https://www.geeksforgeeks.org/different-forms-of-pre-rendering-in-nextjs/",
        height: 628,
        width: 1000,
        byteSize: 89748,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQll2w98HE9S_Ngn2XP9aNIZup0aMJn71yt_hHL365thnodYMFdzsZWRBg&s",
        thumbnailHeight: 94,
        thumbnailWidth: 149,
      },
    },
    {
      kind: "customsearch#result",
      title: "Blog - Next.js 12 | Next.js",
      htmlTitle: "Blog - <b>Next</b>.<b>js</b> 12 | <b>Next</b>.<b>js</b>",
      link: "https://nextjs.org/_next/image?url=%2Fstatic%2Fblog%2Fnext-12%2Fswc.png&w=3840&q=75",
      displayLink: "nextjs.org",
      snippet: "Blog - Next.js 12 | Next.js",
      htmlSnippet: "Blog - <b>Next</b>.<b>js</b> 12 | <b>Next</b>.<b>js</b>",
      mime: "image/",
      fileFormat: "image/",
      image: {
        contextLink: "https://nextjs.org/blog/next-12",
        height: 891,
        width: 2628,
        byteSize: 67411,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJuwmacabeqiUkIQjwc-9byvlfUmyO3sBwTnBaCtl3-FS3mnpyDXJ2YNw&s",
        thumbnailHeight: 51,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "File:Nextjs-logo.svg - Wikipedia",
      htmlTitle: "File:<b>Nextjs</b>-logo.svg - Wikipedia",
      link: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nextjs-logo.svg/1200px-Nextjs-logo.svg.png",
      displayLink: "en.wikipedia.org",
      snippet: "File:Nextjs-logo.svg - Wikipedia",
      htmlSnippet: "File:<b>Nextjs</b>-logo.svg - Wikipedia",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://en.wikipedia.org/wiki/File:Nextjs-logo.svg",
        height: 719,
        width: 1200,
        byteSize: 19632,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMSpYyzRAdO9xS0Jno-qUkHnuksI2uDE2wRCEHbA1dxL-86cSTGHc7wBs&s",
        thumbnailHeight: 90,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Blog - Next.js 13 | Next.js",
      htmlTitle: "Blog - <b>Next</b>.<b>js</b> 13 | <b>Next</b>.<b>js</b>",
      link: "https://nextjs.org/_next/image?url=%2Fstatic%2Fblog%2Flayouts-rfc%2Fapp-folder.png&w=3840&q=75",
      displayLink: "nextjs.org",
      snippet: "Blog - Next.js 13 | Next.js",
      htmlSnippet: "Blog - <b>Next</b>.<b>js</b> 13 | <b>Next</b>.<b>js</b>",
      mime: "image/",
      fileFormat: "image/",
      image: {
        contextLink: "https://nextjs.org/blog/next-13",
        height: 1534,
        width: 3596,
        byteSize: 358189,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYllsuzN_6Sa-Yj3Jr_9RuCYXAy5bGHzvoeXCv5t3LaGxL2DP1lC45gA&s",
        thumbnailHeight: 64,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title:
        "Tutorial: Deploy static-rendered Next.js websites on Azure Static ...",
      htmlTitle:
        "Tutorial: Deploy static-rendered <b>Next</b>.<b>js</b> websites on Azure Static ...",
      link: "https://learn.microsoft.com/en-us/azure/static-web-apps/media/deploy-nextjs/start-nextjs-app.png",
      displayLink: "learn.microsoft.com",
      snippet:
        "Tutorial: Deploy static-rendered Next.js websites on Azure Static ...",
      htmlSnippet:
        "Tutorial: Deploy static-rendered <b>Next</b>.<b>js</b> websites on Azure Static ...",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink:
          "https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-static-export",
        height: 1916,
        width: 2770,
        byteSize: 217608,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQI8MrA-XiDbw7plGpZZbZ-FoM8Wehxnw-9CPpW5Y8ckDXqNz58zVOHgg&s",
        thumbnailHeight: 104,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Serverless Framework: Plugins",
      htmlTitle: "Serverless Framework: Plugins",
      link: "https://raw.githubusercontent.com/serverless-nextjs/serverless-next.js/master/img/logo.gif",
      displayLink: "www.serverless.com",
      snippet: "Serverless Framework: Plugins",
      htmlSnippet: "Serverless Framework: Plugins",
      mime: "image/gif",
      fileFormat: "image/gif",
      image: {
        contextLink:
          "https://www.serverless.com/plugins/serverless-nextjs-plugin",
        height: 800,
        width: 1800,
        byteSize: 174638,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-zkoLe2ZoUgEvmSlREaTGd34bEeAzQzjw1101p3h4YyEWPERLYqR0t-I&s",
        thumbnailHeight: 67,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Blog - Layouts RFC | Next.js",
      htmlTitle: "Blog - Layouts RFC | <b>Next</b>.<b>js</b>",
      link: "https://nextjs.org/_next/image?url=%2Fstatic%2Fblog%2Flayouts-rfc%2Frouting-today.png&w=3840&q=75",
      displayLink: "nextjs.org",
      snippet: "Blog - Layouts RFC | Next.js",
      htmlSnippet: "Blog - Layouts RFC | <b>Next</b>.<b>js</b>",
      mime: "image/",
      fileFormat: "image/",
      image: {
        contextLink: "https://nextjs.org/blog/layouts-rfc",
        height: 605,
        width: 1798,
        byteSize: 102412,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTvGNaahTJSJeu0Pziwebv3Vt73qFryQcNZCY1jBzkHoh9DcmYKg-Ex4Y&s",
        thumbnailHeight: 50,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Serverless Next.js At The Edge",
      htmlTitle: "Serverless <b>Next</b>.<b>js</b> At The Edge",
      link: "https://s3-us-west-2.amazonaws.com/assets.blog.serverless.com/serverless-nextjs/serverless_nextjs_graphics.png",
      displayLink: "www.serverless.com",
      snippet: "Serverless Next.js At The Edge",
      htmlSnippet: "Serverless <b>Next</b>.<b>js</b> At The Edge",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://www.serverless.com/blog/serverless-nextjs",
        height: 2024,
        width: 3100,
        byteSize: 341583,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTuWdMte3bpy2Y3lTeqnSPUNhd-6jGV4y3HThSHzvvP-2QXAAS4geiWsw&s",
        thumbnailHeight: 98,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Blog - Layouts RFC | Next.js",
      htmlTitle: "Blog - Layouts RFC | <b>Next</b>.<b>js</b>",
      link: "https://nextjs.org/_next/image?url=%2Fstatic%2Fblog%2Flayouts-rfc%2Fpage.png&w=3840&q=75",
      displayLink: "nextjs.org",
      snippet: "Blog - Layouts RFC | Next.js",
      htmlSnippet: "Blog - Layouts RFC | <b>Next</b>.<b>js</b>",
      mime: "image/",
      fileFormat: "image/",
      image: {
        contextLink: "https://nextjs.org/blog/layouts-rfc",
        height: 1696,
        width: 3596,
        byteSize: 385884,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbBaFqLtxQeTJYcv1LRF5wUceYz414pLGx_crltTi30g1xMhm_gLRYG_g&s",
        thumbnailHeight: 71,
        thumbnailWidth: 150,
      },
    },
  ],
};
