import Head from "next/head";
import SearchHeader from "../components/SearchHeader";
import SearchResult from "../components/SearchResult";
import res from "../res";

export default function search({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Search Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* search header */}
      <SearchHeader />
      <main className="max-w-5xl mx-auto bg-gray-100">
        {/* search result */}
        <SearchResult />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const markData = true;
  const data = markData
    ? res
    : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${
          process.env.API_KEY
        }&cx=${process.env.CONTEXT_KEY}&q=${context.query.term}${
          context.query.searchType && "&searchType=image"
        }`
      ).then((response) => response.json());

  return {
    props: {
      results: data,
    },
  };
}
