import Head from "next/head";
import SearchHeader from "../components/SearchHeader";
import SearchResult from "../components/SearchResult";
import res from "../res";
import { useRouter } from "next/router";
import ImageResults from "../components/ImageResults";

export default function search({ results }) {
  console.log(results);
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Search Page -{router.query.term}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* search header */}
      <SearchHeader />
      <main className="max-w-5xl px-4 lg:px-0 mx-auto mt-4 ">
        {router.query.searchType === "image" ? (
          <ImageResults results={results} />
        ) : (
          <SearchResult results={results} />
        )}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const startIndex = context.query.start || 1;
  const markData = true;
  const data = markData
    ? res
    : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${
          process.env.API_KEY
        }&cx=${process.env.CONTEXT_KEY}&q=${context.query.term}${
          context.query.searchType && "&searchType=image"
        }&start=${startIndex}`
      ).then((response) => response.json());

  return {
    props: {
      results: data,
    },
  };
}
