import Head from "next/head";
import SearchHeader from "../components/SearchHeader";
import SearchResult from "../components/SearchResult";

export default function search() {
  return (
    <div>
      <Head>
        <title>Search Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* search header */}
      <SearchHeader />
      <main className="max-w-5xl mx-auto bg-gray-100">
        {/* search result */}
        <SearchResult />
      </main>
    </div>
  );
}
